In [1]:
import pandas as pd

In [2]:
df_25 = pd.read_csv(r"C:\Users\vitor\OneDrive\Documentos\Github\VigilIA\dados\raw\DENGBR25.csv")
df_24 = pd.read_csv(r"C:\Users\vitor\OneDrive\Documentos\Github\VigilIA\dados\raw\DENGBR24.csv")

C:\Users\vitor\AppData\Local\Temp\ipykernel_14736\2570981126.py:1: DtypeWarning: Columns (22: ID_OCUPA_N, 44: DT_CHIK_S1, 52: DT_NS1, 54: DT_VIRAL, 74: DT_OBITO) have mixed types. Specify dtype option on import or set low_memory=False.
  df_25 = pd.read_csv(r"C:\Users\vitor\OneDrive\Documentos\Github\VigilIA\dados\raw\DENGBR25.csv")
C:\Users\vitor\AppData\Local\Temp\ipykernel_14736\2570981126.py:2: DtypeWarning: Columns (22: ID_OCUPA_N, 44: DT_CHIK_S1, 45: DT_CHIK_S2, 46: DT_PRNT, 50: DT_SORO, 52: DT_NS1, 54: DT_VIRAL, 56: DT_PCR, 62: DT_INTERNA, 74: DT_OBITO, 85: DT_ALRM, 101: DT_GRAV) have mixed types. Specify dtype option on import or set low_memory=False.
  df_24 = pd.read_csv(r"C:\Users\vitor\OneDrive\Documentos\Github\VigilIA\dados\raw\DENGBR24.csv")

In [3]:
df_24.head()

,TP_NOT,ID_AGRAVO,DT_NOTIFIC,SEM_NOT,NU_ANO,SG_UF_NOT,ID_MUNICIP,ID_REGIONA,ID_UNIDADE,DT_SIN_PRI,...,EVIDENCIA,PLAQ_MENOR,CON_FHD,COMPLICA,TP_SISTEMA,NDUPLIC_N,DT_DIGITA,CS_FLXRET,FLXRECEBI,MIGRADO_W
0,2,A90,2024-03-04,202410,2024,32,320150,32001.0,2446294.0,2024-03-02,...,0.0,0.0,0.0,0.0,0.0,0.0,2023-03-24,0.0,0.0,0.0
1,2,A90,2024-04-17,202416,2024,32,320465,32001.0,2445638.0,2024-04-15,...,0.0,0.0,0.0,0.0,0.0,0.0,2023-03-29,0.0,0.0,0.0
2,2,A90,2024-06-22,202425,2024,32,320520,32002.0,2358298.0,2024-06-11,...,0.0,0.0,0.0,0.0,0.0,0.0,2023-06-22,0.0,0.0,0.0
3,2,A90,2023-12-31,202401,2023,32,320020,32004.0,2448025.0,2023-12-31,...,0.0,0.0,0.0,0.0,0.0,0.0,2023-12-31,0.0,0.0,0.0
4,2,A90,2023-12-31,202401,2023,32,320130,32002.0,7419147.0,2023-12-31,...,0.0,0.0,0.0,0.0,0.0,0.0,2023-12-31,0.0,0.0,0.0

In [4]:
df_25.head()

,TP_NOT,ID_AGRAVO,DT_NOTIFIC,SEM_NOT,NU_ANO,SG_UF_NOT,ID_MUNICIP,ID_REGIONA,ID_UNIDADE,DT_SIN_PRI,...,EVIDENCIA,PLAQ_MENOR,CON_FHD,COMPLICA,TP_SISTEMA,NDUPLIC_N,DT_DIGITA,CS_FLXRET,FLXRECEBI,MIGRADO_W
0,2,A90,2024-12-29,202501,2024,32,320070,32004,2485397.0,2024-12-29,...,0.0,0.0,0.0,0.0,0.0,0.0,2024-12-29,0.0,0.0,0.0
1,2,A90,2024-12-29,202501,2024,32,320020,32004,2448025.0,2024-12-29,...,0.0,0.0,0.0,0.0,0.0,0.0,2024-12-29,0.0,0.0,0.0
2,2,A90,2024-12-29,202501,2024,32,320020,32004,2448025.0,2024-12-29,...,0.0,0.0,0.0,0.0,0.0,0.0,2024-12-29,0.0,0.0,0.0
3,2,A90,2024-12-29,202501,2024,32,320020,32004,2448025.0,2024-12-29,...,0.0,0.0,0.0,0.0,0.0,0.0,2024-12-29,0.0,0.0,0.0
4,2,A90,2024-12-29,202501,2024,32,320020,32004,2448025.0,2024-12-29,...,0.0,0.0,0.0,0.0,0.0,0.0,2024-12-29,0.0,0.0,0.0