In [64]:
import pandas as pd
pd.set_option("display.max_columns", None)   # mostra todas as colunas
pd.set_option("display.max_rows", 20)        # controla quantas linhas aparecem
pd.set_option("display.width", None)

In [65]:
df_prata = pd.read_parquet(r'C:\Users\vitor\OneDrive\Documentos\Github\VigilIA\dados\df_prata.parquet')
municipios = pd.read_csv(r'C:\Users\vitor\OneDrive\Documentos\Github\VigilIA\dados\br_municgestor.csv')
df_bronze = pd.read_parquet(r'C:\Users\vitor\OneDrive\Documentos\Github\VigilIA\dados\df_bronze_26.parquet')

In [66]:

# Lê o arquivo inteiro
with open(r"C:\Users\vitor\OneDrive\Documentos\Github\VigilIA\dados\clima\dados_A001_D_2025-01-01_2026-06-01.csv", encoding="utf-8") as f:
    linhas = f.readlines()

# Extrai metadados das primeiras linhas
nome = linhas[0].split(":")[1].strip()
codigo = linhas[1].split(":")[1].strip()
latitude = float(linhas[2].split(":")[1].strip())
longitude = float(linhas[3].split(":")[1].strip())
data_inicial = linhas[6].split(":")[1].strip()
data_final = linhas[7].split(":")[1].strip()

# Agora lê os dados de medição (pulando cabeçalho)
df_clima_tempo = pd.read_csv(r"C:\Users\vitor\OneDrive\Documentos\Github\VigilIA\dados\clima\dados_A001_D_2025-01-01_2026-06-01.csv", 
                 sep=";", 
                 skiprows=10,  # ajusta conforme o número de linhas de metadados
                 encoding="utf-8")

# Adiciona colunas extras
df_clima_tempo["local"] = nome
df_clima_tempo["codigo_estacao"] = codigo
df_clima_tempo["latitude"] = latitude
df_clima_tempo["longitude"] = longitude
df_clima_tempo["data_inicial"] = data_inicial
df_clima_tempo["data_final"] = data_final

In [67]:
df_clima_tempo.head()

,Data Medicao,"PRECIPITACAO TOTAL, DIARIO (AUT)(mm)",TEMPERATURA DO PONTO DE ORVALHO MEDIA DIARIA (AUT)(°C),"TEMPERATURA MAXIMA, DIARIA (AUT)(°C)","TEMPERATURA MEDIA, DIARIA (AUT)(°C)","UMIDADE RELATIVA DO AR, MEDIA DIARIA (AUT)(%)",Unnamed: 6,local,codigo_estacao,latitude,longitude,data_inicial,data_final
0,2025-01-01,0,"18,8","24,8","21,1","87,3",NaN,BRASILIA,A001,-15.789444,-47.925833,2025-01-01,2026-06-01
1,2025-01-02,0,"17,6","28,2","22,3","76,5",NaN,BRASILIA,A001,-15.789444,-47.925833,2025-01-01,2026-06-01
2,2025-01-03,0,"17,5","29,4","22,9","73,5",NaN,BRASILIA,A001,-15.789444,-47.925833,2025-01-01,2026-06-01
3,2025-01-04,0,"17,4","30,1","23,4","71,2",NaN,BRASILIA,A001,-15.789444,-47.925833,2025-01-01,2026-06-01
4,2025-01-05,0,"18,6","28,9","21,9","83,3",NaN,BRASILIA,A001,-15.789444,-47.925833,2025-01-01,2026-06-01

In [73]:
municipios[municipios['municipio'].str.startswith('Bras')]

       seq  codigo                 municipio codigos_gestor
55      56  120010                 Brasiléia         120010
179    180  150172               Brasil Novo         150172
342    343  170360  Brasilândia do Tocantins         170360
709    710  220196                Brasileira         220196
2352  2353  310855      Brasilândia de Minas         310855
2353  2354  310860         Brasília de Minas         310860
3978  3979  410337        Brasilândia do Sul         410337
5142  5143  500230               Brasilândia         500230
5224  5225  510190                 Brasnorte         510190

In [69]:
municipios.head()

   seq  codigo                municipio codigos_gestor
0    1  110001    Alta Floresta D'Oeste         110001
1    2  110037  Alto Alegre dos Parecis         110037
2    3  110040             Alto Paraíso         110040
3    4  110034         Alvorada D'Oeste         110034
4    5  110002                Ariquemes         110002

In [70]:
municipios[municipios['codigo'] == 520540]

       seq  codigo municipio codigos_gestor
5409  5410  520540     Ceres         520540